export const data = [
  {
    category: "emerging",
    country: "Kenya",
    date: "2024-06-25",
    title: "Economic Growth in Kenya Shows Positive Trends",
    full_text: "",
    images: [
      "https://example.com/image1.jpg",
      "https://example.com/image2.jpg",
    ],
    link: "https://example.com/article1",
  },
  {
    category: "emerging",
    country: "India",
    date: "2024-05-18",
    title: "India's Tech Industry Boom",
    full_text: "",
    images: ["https://example.com/image3.jpg"],
    link: "https://example.com/article2",
  },
  {
    category: "emerging",
    country: "Brazil",
    date: "2024-04-10",
    title: "Brazil's Agricultural Advancements",
    full_text: "",
    images: [],
    link: "https://example.com/article3",
  },
  {
    category: "developed",
    country: "China",
    date: "2024-03-22",
    title: "China's New Trade Policies",
    full_text: "",
    images: [
      "https://example.com/image4.jpg",
      "https://example.com/image5.jpg",
    ],
    link: "https://example.com/article4",
  },
  {
    category: "emerging",
    country: "Nigeria",
    date: "2024-02-15",
    title: "Nigeria's Oil Production Increases",
    full_text: "",
    images: [
      "https://t4.ftcdn.net/jpg/05/64/31/67/360_F_564316725_zE8llusnCk3Sfr9rdfKya6fV7BQbjfyV.jpg",
    ],
    link: "https://example.com/article5",
  },
  {
    category: "frontier",
    country: "Mexico",
    date: "2024-01-30",
    title: "Mexico's Tourism Sector Rebounds",
    full_text: "",
    images: ["https://example.com/image6.jpg"],
    link: "https://example.com/article6",
  },
  {
    category: "frontier",
    country: "Vietnam",
    date: "2023-12-11",
    title: "Vietnam's Manufacturing Surge",
    full_text: "",
    images: [
      "https://example.com/image7.jpg",
      "https://example.com/image8.jpg",
    ],
    link: "https://example.com/article7",
  },
  {
    category: "emerging",
    country: "Turkey",
    date: "2023-11-05",
    title: "Turkey's Inflation Challenges",
    full_text: "",
    images: [],
    link: "https://example.com/article8",
  },
  {
    category: "emerging",
    country: "Indonesia",
    date: "2023-10-19",
    title: "Indonesia's Infrastructure Developments",
    full_text: "",
    images: ["https://example.com/image9.jpg"],
    link: "https://example.com/article9",
  },
  {
    category: "developed",
    country: "Argentina",
    date: "2023-09-28",
    title: "Argentina's Debt Restructuring Efforts",
    full_text: "",
    images: [],
    link: "https://example.com/article10",
  },
  {
    category: "emerging",
    country: "Kenya",
    date: "2024-06-25",
    title: "Economic Growth in Kenya Shows Positive Trends",
    full_text: "",
    images: [
      "https://t4.ftcdn.net/jpg/05/64/31/67/360_F_564316725_zE8llusnCk3Sfr9rdfKya6fV7BQbjfyV.jpg",
      "https://example.com/image1.jpg",
      "https://example.com/image2.jpg",
    ],
    link: "https://example.com/article1",
  },
  {
    category: "emerging",
    country: "India",
    date: "2024-05-18",
    title: "India's Tech Industry Boom",
    full_text: "",
    images: ["https://example.com/image3.jpg"],
    link: "https://example.com/article2",
  },
  {
    category: "emerging",
    country: "Brazil",
    date: "2024-04-10",
    title: "Brazil's Agricultural Advancemesnt",
    full_text: "",
    images: [],
    link: "https://example.com/article3",
  },
];

export const journalReports = [
  {
    title: "The Quiet Power of Rituals in Retirement",
    description:
      "At a time when it’s easy to feel adrift, recurring acts give structure to my days and keep me connected to those I love.",
    readTime: "6",
    subArticles: [
      { text: "The Secret to Finding Love After 60" },
      {
        text: "Two Minnesotans Retired in Cornwall, England. They Love It—Even the Food.",
      },
    ],
  },
  {
    title: "Why, and How, to Break Up With Old Friends",
    description: "",
    readTime: "5",
    subArticles: [],
  },
];
